login: &login
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: raupp
  password: ""
  host: localhost

development:
  database: rd_contacts_db
  <<: *login

test:
  database: rd_contacts_test_db
  <<: *login

production:
  database: bbo_db
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: plyom
  password: plyom2013
  host: localhost
