login: &login
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: raupp
  password: ""
  host: localhost

development:
  database: rd_contacts_db
  <<: *login

test:
  database: rd_contacts_test_db
  <<: *login

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
